# Generated by Django 4.0 on 2021-12-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fail_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('fail_type', models.CharField(blank=True, choices=[('H', 'HTTP error'), ('C', 'No content candidates found (initial scan) or matched (post processing)')], max_length=1, null=True)),
                ('queries', models.ManyToManyField(blank=True, null=True, to='checker.Query')),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match_url', models.CharField(max_length=2048)),
                ('match_display_url', models.CharField(max_length=2048)),
                ('post_scanned', models.BooleanField(default=False)),
                ('post_fail_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('post_fail_type', models.CharField(blank=True, choices=[('H', 'HTTP error'), ('C', 'No content candidates found (initial scan) or matched (post processing)')], max_length=1, null=True)),
                ('perc_of_duplication', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.scanlog')),
            ],
        ),
    ]
