# Generated by Django 3.2.8 on 2021-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20211219_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='queries',
            field=models.ManyToManyField(blank=True, to='checker.Query'),
        ),
    ]
