# Generated by Django 3.2.8 on 2021-12-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_remove_protectedresource_next_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='protected_resource',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
